app = "zynmeet-sfu"
primary_region = "lhr"

[build]

[env]
  NODE_ENV = "production"
  MEDIASOUP_LISTEN_IP = "0.0.0.0"
  MIN_PORT = "10000"
  MAX_PORT = "10100"
  SFU_PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100

  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
